// <auto-generated />
namespace FinalAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MakeNameRequired1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeNameRequired1));
        
        string IMigrationMetadata.Id
        {
            get { return "202603162252104_MakeNameRequired1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
